/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/unmute-theme.ts
 * Command: astryx theme build src/theme/unmute-theme.ts
 * CLI: @astryxdesign/cli@0.6.0
 * Core: @astryxdesign/core@0.6.0
 */

/// <reference path="./unmute.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const unmuteIcons: IconRegistry;
export declare const unmuteTheme: DefinedTheme;
